name: Deploy to Netlify

# Run this workflow on pushes and pull requests to the main branch
on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

      # - name: Run tests
      #   run: yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Push to deploy branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "martinezcj2@gmail.com"
          git config --global user.name "ceejaymar"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin

          if git show-ref --quiet refs/remotes/origin/deploy; then
            git checkout deploy
            git rebase origin/deploy
          else
            git checkout -b deploy
          fi

          git add -f dist/
          git commit -m "Deploy to Netlify"
          git push origin deploy
